### ISSUE TITLE
3.9.7 still work?

### ISSUE THREAD

**Issue by dtomcat** [gozoinks/homebridge-camera-ffmpeg-ufv#20]
Hello,
  I just tried setting this up and it seems homebridge is working; however, after adding this plugin and setting up config.json... it does nothing.  I do not see any cameras when trying to add accessories... and when booting homebridge, I do not see it say anything about find cameras... I can see where it loads the plug in

pi@raspberrypi:~ $ DEBUG=camera-ffmpeg-ufv  homebridge -D
[2018-7-3 00:40:34] Loaded config.json with 0 accessories and 0 platforms.
[2018-7-3 00:40:34] ---
[2018-7-3 00:40:34] Loaded plugin: homebridge-camera-ffmpeg-ufv
[2018-7-3 00:40:34] Registering platform 'homebridge-camera-ffmpeg-ufv.camera-ffmpeg-ufv'
[2018-7-3 00:40:34] ---
Load homebridge-camera-ffmpeg-ufv.camera-ffmpeg-ufv
Setup Payload:...

and that's all i can see other than the QR Code and manual code... says homebridge is running on port.....

Not sure what else to try?  running on a raspberry pi 2.  I compiled FFmpeg to work with OMX.  thanks for any help!  (not sure if it's an issue or not as never had a working version... so may be UFV 3.9.7)

**Comment by dtomcat** [comment]
Here is my config.json

{
    "bridge": {
        "name": "Homebridge",
        "username": "CC:22:3D:E3:CE:30",
        "port": 51826,
        "pin": "012-34-567"
    },
    
    "description": "This is an example configuration file with one fake accessory and one fake platform. You can use this as a template for creating your own configuration file containing devices you actually own.",

    "platform": "camera-ffmpeg-ufv",
    "name": "UniFi Video (ffmpeg)",
    "nvrs": [
      {
        "apiHost": "192.168.0.169",
        "apiPort": 7443,
        "apiProtocol": "https",
        "apiKey": "<actual api is here>"
      }
  ]
}

**Comment by jnanes** [comment]
I'm running 3.9.7 and am functioning with no issues.

**Comment by dtomcat** [comment]
Thanks for the reply!  not sure what the issue is then?  I have it all setup like everything says (i am running on a UAS-XG and not a NVR appliance... think that makes a difference?

**Comment by dtomcat** [comment]
Would you (or anyone) mind showing your config.json?   I just noticed on a full debug of homebridge it displays:
 Loaded config.json with 0 accessories and 0 platforms

so it's not seeing my "platform"

**Comment by jnanes** [comment]
Im running on a ubuntu VM, I dont think it does.

**Comment by dtomcat** [comment]
config.json was it!

i needed a "platforms": [

Thanks for helping!
