### ISSUE TITLE
Stuck at Load homebridge-camera-ffmpeg-ufv.camera-ffmpeg-ufv

### ISSUE THREAD

**Issue by Botts85** [gozoinks/homebridge-camera-ffmpeg-ufv#23]
Hello,

I am trying to setup homebridge-camera-ffmpeg-ufv with my NVR.

My setup is exactly as described in the readme, but I have two IPs for the NVR, and thus two RTSP streams per camera.  This may be why the plugin is having issues.  My cameras live on 10.0.50.x and my NVR lives at 10.0.50.15 and 10.0.1.61.

My Homebridge server lives at 10.0.1.211 and cannot see 10.0.50.15, but can see 10.0.1.61.  However, first listed for each camera is: rtsp://10.0.50.15:7447/"cameraID"e_0 which Homebridge can't reach.  Second listed for each camera is rtsp://10.0.1.61:7447/"cameraID"e_0

Homebridge just sits forever at:
`[8/9/2018, 12:03:03 AM] [Unifi Video (ffmpeg)] Initializing camera-ffmpeg-ufv platform...
Load homebridge-camera-ffmpeg-ufv.camera-ffmpeg-ufv
`
Any help would be greatly appreciated.

Config.json is:
`{
    "bridge": {
        "name": "Homebridge",
        "username": "*",
        "port": 51826,
        "pin": "*"
    },
    "platforms": [
        {
         "platform" : "camera-ffmpeg-ufv",
         "name" : "Unifi Video (ffmpeg)",
         "nvrs" : [
          {
          "apiHost": "10.0.1.61",
          "apiPort": 7447,
          "apiProtocol": "https",
          "apiKey": "*"
          }]
}]}

`

**Comment by adrum** [comment]
@Botts85 I believe your issue might be resolved by this pending pull request: https://github.com/gozoinks/homebridge-camera-ffmpeg-ufv/pull/11

**Comment by jmbwell** [comment]
Thank you. Merged the PR. Will update npm later today.

**Comment by Botts85** [comment]
Thanks, overrideHost worked.  Still having some streaming issues, but those seem unrelated.

**Comment by jnanes** [comment]
is it just me or is NPM showing .8 still?

**Comment by jmbwell** [comment]
Fixed
