### ISSUE TITLE
Automation to receive camera shots on motion

### ISSUE THREAD

**Issue by ryanschmidt** [gozoinks/homebridge-camera-ffmpeg-ufv#25]
It seems this should be possible but it doesn’t seem like I’m able to create an automation that does anything with the camera on motion sensor activity. Anyone able able to get this working?

**Comment by adrum** [comment]
@ryanschmidt If the motion sensor is changed is being triggered (detecting motion), ensure that you are setup to receive notification on each sensor. Also, the sensor and the camera need to be placed in the same HomeKit room.

**Comment by jnanes** [comment]
Austin,

I believe @ryanschmidt is referring to being able to use the sensor, to activate another HomeKit automation

**Comment by adrum** [comment]
Ah, yes. I misread the original message. Let me do some testing and I will report back..

**Comment by jnanes** [comment]
I tried myself as well and I cannot set an action based on the sensors. Sounds like a great idea I would love to be able to

**Comment by adrum** [comment]
Okay I think I figured out how I got confused. The title of the issue asks how to receive snapshots of the camera on motion events. So the way HomeKit handles screenshots is not based on automation events. You can setup camera snapshots on motion based on my first message.

For running automations based on motion events, go to the automation tab and click the plus button on the top right. From there you will select when "A Sensor Detects Something" and then select your camera's motion sensor. You should then be able to configure your actions either based on motion detection or stopped motion detection.

All of this requires a [home hub](https://support.apple.com/en-us/HT207057), such as an Apple TV or a HomePod.

**Comment by jnanes** [comment]
Thanks,  I could have sworn I looked there! Got it.

**Comment by ryanschmidt** [comment]
Thank you! I never checked on the sensors setting. This seems to work great and as expected. So cool.
