### ISSUE TITLE
One motion sensor triggered, two alerts sent. 

### ISSUE THREAD

**Issue by jfmoots** [gozoinks/homebridge-camera-ffmpeg-ufv#28]
I have two cameras in one room. When either motion sensor gets triggered it causes an alert to be sent to the Apple Home app with a picture from each camera.

**Comment by jfmoots** [comment]
Looks like this might be working as designed. I'm thinking it's HomeKit that's doing this and that HomeKit, by design, sends a pic from all cameras in a given room when a motion sensor in that room is triggered.

**Comment by jmbwell** [comment]
Indeed. HomeKit will send multiple alerts, one for each camera assigned to the room, when any motion sensor in that room senses motion. 

This surprised me too. I don’t entirely mind.
