### ISSUE TITLE
iOS 13 Ready?

### ISSUE THREAD

**Issue by roycepope** [gozoinks/homebridge-camera-ffmpeg-ufv#41]
Anybody know if this plugin is good to go for iOS 13? I really like this plugin and it would be a real shame for it to be broken we updating to iOS 13. Has anybody tried the iOS 13 beta with this?

**Comment by jnanes** [comment]
Plugin works but push notifications with screenshots are broken completely.

**Comment by JJJ** [comment]
Audio/video works great in iOS 13. I don’t use notifications, so I’m not sure about them either way.

Here’s a screen shot from the Home app on my phone running the latest beta:
![F895658E-54BF-4C37-966A-32944CF625A3](https://user-images.githubusercontent.com/88951/64394157-65f82880-d01a-11e9-84c2-70df04711305.png)

**Comment by roycepope** [comment]
Thanks guys, it sounds like existing functionality is going to be intact. Will open future issues if they arise when iOS 13 releases.

**Comment by ryanschmidt** [comment]
I can confirm that push notifications are busted in iOS 13.

**Comment by jmbwell** [comment]
I get thumbnails sometimes, I don’t get them sometimes. I need to investigate. Open to input.

**Comment by jnanes** [comment]
Worst. Any idea if the screenshot notifications are able to be fixed?

**Comment by roycepope** [comment]
Should we wait for iOS 13.1 to be released by the end of the month? I hear this is supposed to fix a lot of things for HomeKit.

**Comment by ryanschmidt** [comment]
I do think 13.1 is supposed to have some fixes. I guess we won't know if that will affect this or not. I assume if they changed how the notification images work others will need to update their apps as well.

**Comment by ryanschmidt** [comment]
Just noticed that I am getting image previews to MacOS HomeKit but the same notification doesn't send a preview to iOS or WatchOS. For that reason, I don't think this is something that needs changed with the homebridge plugin.

**Comment by ryanschmidt** [comment]
It appears to be this same issue https://github.com/KhaosT/homebridge-camera-ffmpeg/issues/332

**Comment by jmbwell** [comment]
Combining the camera with the motion sensor into a composite device apparently helps, and might actually be an improvement for this plugin. 

This would not fix rich notifications with other sensors in the room, but that sounds like a constraint introduced to HomeKit by Apple.

**Comment by vddgil** [comment]
> Audio/video works great in iOS 13. I don’t use notifications, so I’m not sure about them either way.
> 
> Here’s a screen shot from the Home app on my phone running the latest beta:
> ![F895658E-54BF-4C37-966A-32944CF625A3](https://user-images.githubusercontent.com/88951/64394157-65f82880-d01a-11e9-84c2-70df04711305.png)

Hey @JJJ Hom did you managed to have sound with this plugin, for me it's just disabled ...

Thanks a lot !

Gil

**Comment by roycepope** [comment]
@vddgil Confirmed _no_ sound at all on iOS 13.1.2

**Comment by JJJ** [comment]
Here’s a modified version of my config. This likely requires FFMpeg itself to be compiled as per the instructions in the Wiki here in this repository. I went through various different sets of flags, and I’m not 100% confident what they are, but I’ll post them here if I can pull them out of FFMpeg.

```
        {
            "platform": "Camera-ffmpeg",
            "cameras": [
                {
                    "name": "Whatever",
                    "videoConfig": {
                        "source": "-rtsp_transport tcp -re -i rtsp://your-cloud-key-url",
                        "stillImageSource": "-i http://your-camera-ip/snap.jpeg",
                        "additionalCommandline": "-preset slow -profile:v high -level 4.2 -x264-params intra-refresh=1:bframes=0",
                        "vcodec": "h264_omx",
                        "packetSize": 188,
                        "audio": true,
                        "maxStreams": 2,
                        "maxWidth": 1920,
                        "maxHeight": 1080,
                        "maxFPS": 15,
                        "maxBitrate": 300,
                        "mapaudio": "0:0",
                        "mapvideo": "0:1"
                    }
                },
            }
```

I’m currently running the 13.2 beta, also with sound. It’s been pretty inconsistent between iOS and iPadOS versions. Sometimes streams would completely fail on my iPhone only and work fine in the Home app on my Mac, etc…

**Comment by vddgil** [comment]
Hello @JJJ and thanks for your answer.
What do you mean by "in the Wiki here in this repository.". I can't find any instructions on how to compile ffmpeg in the wiki ...

Thanks in advance !

Gil

**Comment by ryanschmidt** [comment]
Still no luck with this. I'm getting snapshots for other plugins like `homebridge-ring` so I'm wondering if there is something required to get snapshots to work again here for iOS 13. Any pointers would be appreciated!

**Comment by JJJ** [comment]
@vddgil Sorry; from the Wiki on the original fork this repo was born from:

https://github.com/KhaosT/homebridge-camera-ffmpeg/wiki/Raspberry-PI

I happen to be setting up a new HomeBridge instance from scratch, so I'll be testing this momentarily.

`ffmpeg -sample_fmts` will output a bunch of helpful stuff, including `configuration:` which is where you can see what flags its been compiled with.

**Comment by JJJ** [comment]
@vddgil Sooo.... I followed the instructions in the Wiki link above, and nothing works - not even basic video. It appears I have some more research to do.

**Comment by ryanschmidt** [comment]
Still stuck on this :(

Is this related? https://github.com/KhaosT/homebridge-camera-ffmpeg/wiki/iOS-13-and-Photo-Notifications?utm_source=share&utm_medium=ios_app&utm_name=iossmf

**Comment by jnanes** [comment]
any news on this?

**Comment by ryanschmidt** [comment]
No news. Just sadness and image-less notifications.

**Comment by jnanes** [comment]
About to give up hope. Still sitting back on ios12

**Comment by ukypayne** [comment]
I'm on iOS 13 and have the regular camera options working fine.

I didn't know the snapshot & push notification was an option. Is there active development in this UFV branch to possibly get this to work? I tried the flags that @JJJ listed above but had nothing actually appear.

**Comment by jnanes** [comment]
Billy,

You have the push notification with screenshots working? Can you clarify how as it doesn’t work for others afaik?

**Comment by ukypayne** [comment]
@jnanes No, I do not have screenshots working. I said I had the old functions of just seeing the camera.

**Comment by jnanes** [comment]
Sorry I was confused, as the old function was to receive notifications...

**Comment by cburn** [comment]
> Combining the camera with the motion sensor into a composite device apparently helps, and might actually be an improvement for this plugin.
> 
> This would not fix rich notifications with other sensors in the room, but that sounds like a constraint introduced to HomeKit by Apple.

Yep, that seems to have fixed it. My PR #43 fixes the rich notifications by adding the motion sensor as a service on the camera.

**Comment by jnanes** [comment]
@cburn sorry for being naive, is there a way I can apply this patch manually or do I need to wait for it to be merged?

**Comment by cburn** [comment]
@jnanes you can clone from my fork to get it for now - https://github.com/cburn/homebridge-camera-ffmpeg-ufv

**Comment by jnanes** [comment]
::googles Clone::

Ok thank you sir!

**Comment by jnanes** [comment]
@cburn I was able to clone your fork  but am not getting the rich notifications on iOS 13. Is there any change needed to my config file or anything else?

**Comment by cburn** [comment]
@jnanes you'll have to manually install this as well. Might be easier to wait for it to be updated on NPM.

```
npm -g uninstall homebridge-camera-ffmpeg-ufv
cd <to where you cloned my fork to>
npm i
npm install -g
```

**Comment by jmbwell** [comment]
Yeah sit tight cowpokes, got a house full of people and Christmas trees going up. Will try again this evening

**Comment by jnanes** [comment]
No worries, after I broke my instance by trying to manually install I reverted my snapshot and I'm now waiting patiently.

Thanks for all the hard work!!

**Comment by jmbwell** [comment]
Okay, I've updated npm with the latest patch. Thanks for all the effort y'all
