### ISSUE TITLE
Push Notifications no longer include image in iOS 13

### ISSUE THREAD

**Issue by ryanschmidt** [gozoinks/homebridge-camera-ffmpeg-ufv#42]
Are others experiencing this as well? I’ve upgraded to iOS 13 and also upgraded all Homebridge plugins but notifications no longer include images.

Needless to say, thank you for this great plugin! Just wanted to report the issue to confirm that I’m not just missing something that I might need to update.

**Comment by jnanes** [comment]
Yes I tested during beta and can confirm i experiences the same. I downgraded and am back to ios12. I really don’t want to give up the feature

**Comment by ryanschmidt** [comment]
Closing in favor of this more informative thread https://github.com/gozoinks/homebridge-camera-ffmpeg-ufv/issues/41
