### ISSUE TITLE
Crashing homebridge

### ISSUE THREAD

**Issue by HajLender** [gozoinks/homebridge-camera-ffmpeg-ufv#7]
Hi,

thank you for this plugin, it used to work great on my previous homebridge
I am running homebridge on iMac now (used to run on my synology NAS) and I have an issue.

I installed the ffmpeg binaries from ffmpeg.org and installed your plugin. I can find the cameras on my phone, but now comes the issue:

When I click on the still from the camera to view the video I am getting an error and the whole homebridge crashes. I get following in terminal:

-rtsp_transport http -re -i rtsp://192.168.1.103:7447/5967ba0ee4b0b63b7a1a8af3_0?apiKey=jdMGHJ7KDcJa7H0aaaaa1aOxhK0KMBhA -threads 0 -vcodec libx264 -an -pix_fmt yuv420p -r 30 -f rawvideo -tune zerolatency -vf scale=1280:720 -b:v 299k -bufsize 299k -payload_type 99 -ssrc 1 -f rtp -srtp_out_suite AES_CM_128_HMAC_SHA1_80 -srtp_out_params 09q9WCfc7xxxxxxxxxxxBAcuU3pYM srtp://192.168.1.151:61434?rtcpport=61434&localrtcpport=61434&pkt_size=1378
events.js:137
      throw er; // Unhandled 'error' event
      ^

Error: spawn ffmpeg ENOENT
    at _errnoException (util.js:1003:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:201:19)
    at onErrorNT (internal/child_process.js:389:16)
    at process._tickCallback (internal/process/next_tick.js:152:19) 

EDIT: problem solved by correct installation of ffmpeg
I used this command:

brew install ffmpeg --with-fdk-aac --with-ffplay --with-freetype --with-frei0r --with-libass --with-libvo-aacenc --with-libvorbis --with-libvpx --with-opencore-amr --with-openjpeg --with-opus --with-rtmpdump --with-schroedinger --with-speex --with-theora --with-tools

David

**Comment by gozoinks** [comment]
👍
